name: vcstool

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - {os: ubuntu-18.04, python-version: "3.5"}
          - {os: ubuntu-18.04, python-version: "3.6"}
          - {os: ubuntu-20.04, python-version: "3.7"}
          - {os: ubuntu-20.04, python-version: "3.8"}
          - {os: ubuntu-20.04, python-version: "3.9"}
          - {os: ubuntu-20.04, python-version: "3.10"}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.cfg.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyyaml
          pip install pytest-flake8
      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics
      - name: Test with pytest
        run: |
          git config --global --add init.defaultBranch master
          git config --global --add advice.detachedHead true
          pytest -s -v